name: Summarize Slack Thread

on:
  workflow_dispatch:
    inputs:
      channel_id:
        description: 'Slack channel ID'
        required: true
        type: string
      message_ts:
        description: 'Message timestamp'
        required: true
        type: string
      user_id:
        description: 'User who added the reaction'
        required: false
        type: string

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run summarizer
        env:
          AI_PROVIDER: ${{ vars.AI_PROVIDER || 'gemini' }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_OWNER: ${{ vars.GITHUB_REPO_OWNER }}
          GITHUB_REPO_NAME: ${{ vars.GITHUB_REPO_NAME }}
          CHANNEL_ID: ${{ inputs.channel_id }}
          MESSAGE_TS: ${{ inputs.message_ts }}
        run: |
          ./gradlew run --args="$CHANNEL_ID $MESSAGE_TS"
